name: todo_ai
description: "A new Flutter project with AI-powered voice TODOs."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.1
  ready_widgets: ^0.0.1

  # State Management
  get: ^4.7.2

  # Voice Input/Output
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # AI & Networking
  dio: ^5.9.0
  dart_openai: ^5.1.0 # For OpenAI GPT integration

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Firebase (optional - if you want cloud sync)
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true
