name: todo_ai
description: "A new Flutter project with AI-powered voice TODOs."
publish_to: 'none'

version: 0.0.1+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.3.0
  font_awesome_flutter: ^10.9.1
  ready_widgets: ^0.0.1
  hugeicons: ^0.0.11
  ndialog: ^4.5.0+1

  # State Management
  get: ^4.7.2

  # Voice Input/Output
  speech_to_text: ^7.3.0
  flutter_tts: ^4.2.3

  # AI & Networking
  dio: ^5.9.0
  dart_openai: ^5.1.0 # For OpenAI GPT integration
  flutter_dotenv: ^5.1.0

  # Local Database
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5

  # Firebase (optional - if you want cloud sync)
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1

  # Utils
  intl: ^0.20.2
  shared_preferences: ^2.5.3
  connectivity_plus: ^6.1.5
  uuid: ^4.5.1
  gap: ^3.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.11

flutter:
  uses-material-design: true

  # Assets
  assets:
    - .env
    # - .env.prod
    - assets/
    - assets/logo/
    # - assets/images/
    # - assets/icon/
    # - assets/svg/
    - assets/gifs/

flutter_launcher_icons:
  android: launcher_icon
  image_path: assets/logo/logo.png
  ios: true
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#00508f"
  image: assets/logo/splash transparent.png
  android_12:
    image: assets/logo/splash transparent.png
    color: "#00508f"
