// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzY3uggmTAK3Z5zJs6vPZihao7QNhX0YI',
    appId: '1:573223127111:web:396bbe9dcc487fc3d8c962',
    messagingSenderId: '573223127111',
    projectId: 'todo-ai-app-2692d',
    authDomain: 'todo-ai-app-2692d.firebaseapp.com',
    storageBucket: 'todo-ai-app-2692d.firebasestorage.app',
    measurementId: 'G-X8Y0EK92VR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBm-bckJiN93C8Srtc8yXcGaDQ2uxVE-ig',
    appId: '1:573223127111:android:cd6db907f7e71a47d8c962',
    messagingSenderId: '573223127111',
    projectId: 'todo-ai-app-2692d',
    storageBucket: 'todo-ai-app-2692d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQhPcaCpKxUN2PJW-l3UAc_Eiw5ueOw3c',
    appId: '1:573223127111:ios:25f32b5fd5338c4fd8c962',
    messagingSenderId: '573223127111',
    projectId: 'todo-ai-app-2692d',
    storageBucket: 'todo-ai-app-2692d.firebasestorage.app',
    iosBundleId: 'com.example.todoAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQhPcaCpKxUN2PJW-l3UAc_Eiw5ueOw3c',
    appId: '1:573223127111:ios:25f32b5fd5338c4fd8c962',
    messagingSenderId: '573223127111',
    projectId: 'todo-ai-app-2692d',
    storageBucket: 'todo-ai-app-2692d.firebasestorage.app',
    iosBundleId: 'com.example.todoAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzY3uggmTAK3Z5zJs6vPZihao7QNhX0YI',
    appId: '1:573223127111:web:a045f9cdf176b42ed8c962',
    messagingSenderId: '573223127111',
    projectId: 'todo-ai-app-2692d',
    authDomain: 'todo-ai-app-2692d.firebaseapp.com',
    storageBucket: 'todo-ai-app-2692d.firebasestorage.app',
    measurementId: 'G-457VY0R1VT',
  );
}
